apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      env: tomcat
  template:
    metadata:
      name: ng-pod
      labels:
        env: tomcat
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: tomcat
        image: saravak/tomcat8
        ports:
        - containerPort: 80
          protocol: TCP
